sudo: required
language: julia
dist: xenial
python:
  - "3.6"
git:
  depth: 3
  quiet: true
julia:
  - 1.1
env:
  - PYTHON="/Users/travis/Library/Python/3.6/bin/python"
install:
  - which python
  - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python get-pip.py
  - sudo sh ./deps/install.sh
os:
  - osx
  - linux
notifications:
  email: false


  