language: julia
julia:
  - 1.1
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
dist: trusty
sudo: true
os:
  - osx
  - linux
install:
    - sudo python3 -m pip install --upgrade pip
    - sudo python3 -m pip install tensorflow==1.14
notifications:
  email: false