sudo: required
language: julia
python:
  - "3.6"
git:
  depth: 3
  quiet: true
julia:
  - 1.1
addons:
  apt:
    packages:
      - "python3.6"
env:
  global:
    - PYTHON="/Users/travis/Library/Python/3.6/bin/python"
install:
  - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.6 get-pip.py
  - sudo sh ./deps/install.sh
dist: trusty
os:
  - osx
  - linux
notifications:
  email: false


  