language: julia
julia:
  - 1.1
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
    - pip install tensorflow==1.14
dist: trusty
sudo: true
os:
  - osx
  - linux
notifications:
  email: false